"""adding new tables

Revision ID: e2d7e1e4a4f0
Revises: 
Create Date: 2021-07-05 20:24:23.608538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d7e1e4a4f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('withdrawl', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintable')
    # ### end Alembic commands ###
